"""empty message

Revision ID: 0002affd80c9
Revises: efe9c1e096fb
Create Date: 2022-05-26 14:55:56.916249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002affd80c9'
down_revision = 'efe9c1e096fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login__data', sa.Column('user_id', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login__data', 'user_id')
    # ### end Alembic commands ###
