"""empty message

Revision ID: 2c660a206adf
Revises: 4b0d80b147fe
Create Date: 2022-06-02 22:27:06.671461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c660a206adf'
down_revision = '4b0d80b147fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local', sa.String(length=200), server_default='1', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('local')

    # ### end Alembic commands ###
