"""empty message

Revision ID: 2d30be51d869
Revises: 20c00eac35c8
Create Date: 2023-05-10 20:52:55.386796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d30be51d869'
down_revision = '20c00eac35c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('add_marker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_name', sa.String(length=200), nullable=True))
        batch_op.drop_column('image_dir')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('add_marker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_dir', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('img_name')

    # ### end Alembic commands ###
