"""empty message

Revision ID: 3270ac23bbe7
Revises: f78bdfa035ad
Create Date: 2023-04-15 20:44:36.315608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3270ac23bbe7'
down_revision = 'f78bdfa035ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_name', sa.String(length=200), nullable=True))

    with op.batch_alter_table('signup__data', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_signup__data_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_signup__data_user_id'), ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signup__data', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_signup__data_user_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_signup__data_email'), type_='unique')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('img_name')

    # ### end Alembic commands ###
