"""empty message

Revision ID: 639434d696bc
Revises: cf402a5d205b
Create Date: 2023-05-14 14:45:42.157693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639434d696bc'
down_revision = 'cf402a5d205b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health__data')
    op.drop_table('exercise__data')
    with op.batch_alter_table('signup__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_img', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signup__data', schema=None) as batch_op:
        batch_op.drop_column('profile_img')

    op.create_table('exercise__data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_type', sa.VARCHAR(length=200), nullable=False),
    sa.Column('exercise_time', sa.INTEGER(), nullable=False),
    sa.Column('exercise_note', sa.TEXT(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['signup__data.id'], name='fk_exercise__data_user_id_signup__data', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health__data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('height', sa.INTEGER(), nullable=False),
    sa.Column('weight', sa.INTEGER(), nullable=False),
    sa.Column('body_fat', sa.INTEGER(), nullable=False),
    sa.Column('body_muscle', sa.INTEGER(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['signup__data.id'], name='fk_health__data_user_id_signup__data', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
