"""empty message

Revision ID: 64bc212abfd6
Revises: 8d20832158be
Create Date: 2022-05-22 16:55:35.895528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64bc212abfd6'
down_revision = '8d20832158be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('body_fat', sa.Integer(), nullable=False),
    sa.Column('body_muscle', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('bmi', sa.Integer(), nullable=False),
    sa.Column('body_fat', sa.Integer(), nullable=False),
    sa.Column('body_muscle', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('my_profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_profile',
    sa.Column('user_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('height', sa.INTEGER(), nullable=True),
    sa.Column('weight', sa.INTEGER(), nullable=True),
    sa.Column('body_fat', sa.INTEGER(), nullable=True),
    sa.Column('skeletal_muscle', sa.INTEGER(), nullable=True),
    sa.Column('health_level', sa.VARCHAR(length=200), nullable=True),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bmi', sa.INTEGER(), nullable=False),
    sa.Column('body_muscle', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('user_name')
    )
    op.drop_table('profile_data')
    op.drop_table('health_data')
    # ### end Alembic commands ###
