"""empty message

Revision ID: 7bf9b014e1a3
Revises: 0002affd80c9
Create Date: 2022-05-26 15:34:15.892387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf9b014e1a3'
down_revision = '0002affd80c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'login__data', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'login__data', type_='unique')
    # ### end Alembic commands ###
