"""empty message

Revision ID: 85a26ce843cc
Revises: 7f28f1ee28ad
Create Date: 2023-05-03 15:01:09.591722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a26ce843cc'
down_revision = '7f28f1ee28ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['signup__data.id'], name=op.f('fk_follow_notification_sender_id_signup__data')),
    sa.ForeignKeyConstraint(['user_id'], ['signup__data.id'], name=op.f('fk_follow_notification_user_id_signup__data')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follow_notification'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow_notification')
    # ### end Alembic commands ###
