"""empty message

Revision ID: 86d84825a950
Revises: 70712cd3e48e
Create Date: 2022-05-29 00:18:38.722012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86d84825a950'
down_revision = '70712cd3e48e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health__data', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
