"""empty message

Revision ID: 8af9eee3741c
Revises: f8e720ad639c
Create Date: 2022-05-10 01:12:58.770954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8af9eee3741c'
down_revision = 'f8e720ad639c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_profile', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('my_profile', 'id')
    # ### end Alembic commands ###
