"""empty message

Revision ID: 8d20832158be
Revises: 8af9eee3741c
Create Date: 2022-05-22 15:35:13.237883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d20832158be'
down_revision = '8af9eee3741c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_profile', sa.Column('bmi', sa.Integer(), nullable=False))
    op.add_column('my_profile', sa.Column('body_muscle', sa.Integer(), nullable=False))
    op.alter_column('my_profile', 'height',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('my_profile', 'weight',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('my_profile', 'body_fat',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('my_profile', 'user_name')
    op.drop_column('my_profile', 'skeletal_muscle')
    op.drop_column('my_profile', 'health_level')
    op.drop_column('my_profile', 'create_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_profile', sa.Column('create_date', sa.DATETIME(), nullable=False))
    op.add_column('my_profile', sa.Column('health_level', sa.VARCHAR(length=200), nullable=True))
    op.add_column('my_profile', sa.Column('skeletal_muscle', sa.INTEGER(), nullable=True))
    op.add_column('my_profile', sa.Column('user_name', sa.VARCHAR(length=200), nullable=False))
    op.alter_column('my_profile', 'body_fat',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('my_profile', 'weight',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('my_profile', 'height',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('my_profile', 'body_muscle')
    op.drop_column('my_profile', 'bmi')
    # ### end Alembic commands ###
