"""empty message

Revision ID: 97203df0bd15
Revises: 
Create Date: 2022-05-10 00:54:39.157894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97203df0bd15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_profile',
    sa.Column('user_name', sa.String(length=200), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('body_fat', sa.Integer(), nullable=True),
    sa.Column('skeletal_muscle', sa.Integer(), nullable=True),
    sa.Column('health_level', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('my_profile')
    # ### end Alembic commands ###
