"""empty message

Revision ID: a8f3dc20f963
Revises: ae186122cf18
Create Date: 2023-05-14 17:08:58.986322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f3dc20f963'
down_revision = 'ae186122cf18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('add_marker', schema=None) as batch_op:
        batch_op.drop_column('latitude')
        batch_op.drop_column('longitude')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('add_marker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('latitude', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
