"""empty message

Revision ID: ae186122cf18
Revises: 639434d696bc
Create Date: 2023-05-14 16:26:05.284220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae186122cf18'
down_revision = '639434d696bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('add_marker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('subject', sa.String(length=200), nullable=False))
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('add_marker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('subject')
        batch_op.drop_column('local')

    # ### end Alembic commands ###
