"""empty message

Revision ID: cf402a5d205b
Revises: d5c19e4bdc78
Create Date: 2023-05-14 13:27:16.978756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf402a5d205b'
down_revision = 'd5c19e4bdc78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('add_marker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_dir', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('add_marker', schema=None) as batch_op:
        batch_op.drop_column('image_dir')

    # ### end Alembic commands ###
