"""empty message

Revision ID: d4b6a133687e
Revises: 85a26ce843cc
Create Date: 2023-05-10 19:23:40.037007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b6a133687e'
down_revision = '85a26ce843cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('add_marker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_dir', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['signup__data.id'], name=op.f('fk_add_marker_user_id_signup__data'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_add_marker'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('add_marker')
    # ### end Alembic commands ###
