"""empty message

Revision ID: d5c19e4bdc78
Revises: d4b6a133687e
Create Date: 2023-05-10 20:40:33.217189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c19e4bdc78'
down_revision = 'd4b6a133687e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('add_marker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_name', sa.String(length=200), nullable=True))
        batch_op.drop_column('image_dir')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('add_marker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_dir', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('img_name')

    # ### end Alembic commands ###
