"""empty message

Revision ID: f78bdfa035ad
Revises: f1e1a9050b1b
Create Date: 2023-03-30 15:18:45.395761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78bdfa035ad'
down_revision = 'f1e1a9050b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signup__data', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signup__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=150), nullable=False))

    # ### end Alembic commands ###
