"""empty message

Revision ID: f8e720ad639c
Revises: 97203df0bd15
Create Date: 2022-05-10 00:57:01.884147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e720ad639c'
down_revision = '97203df0bd15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_profile', sa.Column('create_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('my_profile', 'create_date')
    # ### end Alembic commands ###
